# Generated by Django 2.2.5 on 2019-09-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auth_image',
            new_name='profile_image',
        ),
    ]
