# Generated by Django 2.2.5 on 2019-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190923_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
